# Generated by Django 5.0.2 on 2025-08-11 08:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created_at',
        ),
        migrations.AddField(
            model_name='session',
            name='jsonUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
